repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-yaml
        # args:
        #   - "-c __GIT_WORKING_DIR__/.linter-config/.yamllint"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_checkov
        exclude: "[examples|test]/.*$"
        args:
          - "--args=--config-file __GIT_WORKING_DIR__/.linter-config/.checkov.yml"
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.17.2
    hooks:
      - id: ansible-lint
        # args:
        #  # - "--args=--config-file __GIT_WORKING_DIR__/.ansible-lint"
        #  # - "--args=--config-file .ansible-lint"
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit
  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
